components/help/overview/gallery-1.js
components/help/overview/gallery-2.js
components/help/overview/gallery-3.js
components/layout/header.js
components/operators/edit.js
components/operators/new.js
components/ui/login.js
components/users/new.js
constants/help.js
pages/about.js
pages/help.js

Closes translation localisations for:
- about page
- help page
- user and operator sign up form labels
- header logged in state

Apply translation localisations

---

components/ui/partner-card.js
css/components/ui/_partner-card.scss
modules/partners.js
pages/about.js

**NOTE:** Currently no partner records, therefore partners not rendered.
Closes https://www.pivotaltracker.com/story/show/154403530

About: Implement partners grid

---

css/components/ui/_table.scss
modules/observations.js
pages/observations.js
selectors/observations/parsed-chart-observations.js
selectors/observations/parsed-table-observations.js

Closes task row 60.
**Report column:**
**No report example:**

Observations:  Add report column and report items to observations table

---

components/ui/doc-card.js

Producers: Open annex file in a new tab

---

components/operators-detail/observations/by-category.js
css/components/form/checkbox.scss
modules/observations.js
pages/observations.js

**Todo:**
**Add feature to toggle columns:**

Observations: add interaction to toggle table columns

---

modules/user.js

Closes https://www.pivotaltracker.com/story/show/154672992

User: Ensure page reload to render appropriate user state data

---

components/ui/search.js

Fix search component search and deleting search content error

---

components/layout/with-tracker.js
package.json
pages/about.js
pages/help.js
pages/index.js
pages/observations.js
pages/operators-detail.js
pages/operators-edit.js
pages/operators-new.js
pages/operators.js
pages/signup.js

Add Google Analytics to all pages

---

components/operators-detail/observations/by-category-illegality.js
css/components/ui/_observations-by-illegality.scss

**Closes:**
*Layout of close button on different viewport widths:*

Producer Observations: Add close info panel functionality

---

css/components/layout/_header.scss
css/components/page/_static-header.scss
css/components/page/_static-section.scss
css/components/ui/_card.scss
css/components/ui/_intro.scss
css/settings.scss
pages/index.js

Global design fixes

---

components/help/faqs.js
components/help/overview.js
components/help/overview/gallery-3.js
constants/help.js
css/components/ui/_card.scss
css/components/ui/_gallery.scss
modules/help.js
modules/index.js
pages/help.js

Help : Retrieve and render FAQs in the help tabs

---

components/ui/doc-modal.js

Producers: Update new document localisation

---

pages/about.js

Partners: remove static text and related image

---

components/operators-detail/documentation/documents-provided.js
components/ui/chart-legend.js

Documentation: Move documentation availability proportion to legend

---

components/ui/doc-annexes-modal.js

**Fix layout:**
*Before:*
*After:*

Fix doc annex form field layout

---

components/ui/navigation-list.js
pages/terms.js

**Closes:**
Adds initial page setup with no content:

Terms: Add initial terms of service page

---

components/operators-detail/documentation/documents-by-fmu.js
components/operators-detail/documentation/documents-by-operator.js
components/operators-detail/documentation/documents-provided.js
selectors/operators-detail/documentation.js
utils/documentation.js

**Closes:**
*Note:* Consider different implementation where category position provided with object, however currently several different components reliant on the existing data structure (i.e. chart).

Documentation: Order documentation categories based on category position

---

components/operators-detail/documentation.js
components/operators-detail/documentation/documents-by-stacked-timeline.js
components/ui/stacked-timeline.js
css/components/ui/_stacked-timeline.scss
css/index.scss
utils/stacked-timeline.js

@mbarrenechea please review approach and test behaviour.
Closes:

Add stack timeline chart for documentation

---

components/operators-detail/documentation/documents-by-stacked-timeline.js
components/ui/stacked-timeline.js
css/components/ui/_stacked-timeline.scss

**Closes:** 
- ShouldComponentUpdate false?
- Use the reference of the html node prop
- Styles (axis)
- Max date = current date + year (*made to 2 years*)
*Note:* Tooltip (start date, end date and status) **NOT** included in this PR.

Documentation: enhance stackedtimeline chart styling

---

constants/operators.js
css/components/form/select.scss
modules/operators-ranking.js
pages/operators.js
services/layerManager.js

Add boundaries to included countries.
@mbarrenechea would we please be able to review in terms of the map/layer managers. The country boundaries have been added as layers but need to ensure consistent behaviour when working with the filters used on this page.

Add country boundaries

---

components/layout/layout.js
components/operators/filters.js
components/ui/filters.js
components/ui/search.js
pages/observations.js
pages/operators-detail.js
utils/analytics.js

Please confirm implementation.

Add google analytics custom events

---

pages/about.js

Closes Task: `The priority order doesn't work`

About: Prioritise donors

---

modules/donors.js

Closes `The site in French display the text in English under the donors logos`

About: Apply donor language localisation

---

constants/operators.js
index.js
package.json
utils/gladAlerts.js

Adds GLAD alerts tiles to producers map:

Operators: Add glad alerts operators map

---

components/operators-detail/fmus.js
constants/operators-detail.js

Closes `Issue fixed on the ranking page map but not on the map of FMUs in each company profile`

Operator Detail: Add legend to FMU map

---

components/map/popup.js
components/operators-detail/documentation.js
components/operators-detail/documentation/documents-by-fmu.js
constants/operators.js
package.json
utils/documentation.js

@mbarrenechea scrollTo not consistently working
*Note:* active tab not being stored in the store in this PR.

Operator: Add link from FMU map popup to FMU documentation

---

components/map/popup.js
components/ui/fmu-card.js

Closes: `and link to the list of observations for this FMU`

Operators: Add links to fmu observations

---

components/operators-detail/documentation/documents-by-stacked-timeline.js
components/ui/chart-legend.js
constants/rechart.js
css/components/ui/_chart-legend.scss
css/components/ui/_stacked-timeline.scss

Chronological: Add chart legend

---

components/ui/fmu-card.js
css/components/ui/_fmu-card.scss
modules/operators-detail-fmus.js

FMU: Fix population of sidebar GLAD alerts data

---

components/ui/navigation-list.js
components/users/newsletter.js
index.js
modules/user.js
pages/newsletter.js

This PR adds:
- Newsletter page:
- Link inside footer

Newsletter

---

.eslintrc
components/operators-detail/documentation/documents-by-operator.js
components/operators-detail/documentation/documents-by-stacked-timeline.js
components/operators-detail/documentation/documents-certification.js
components/operators-detail/fmus.js
components/operators-detail/observations/by-category-illegality.js
components/operators-detail/observations/by-category.js
components/operators-detail/observations/total.js
components/operators-detail/overview/gallery-1.js
index.js
jsconfig.json
package.json
pages/signup.js
postcss.config.js

Eslint config and components formatting (on operators-detail only, for now).

Formatted operators-detail components

---

components/operators-detail/documentation/documents-provided.js
components/operators-detail/documentation/documents-timeline.js
css/components/ui/_doc-operator-detail.scss

translations for the timeline tooltip & styles

---

components/database/table.js
components/ui/doc-modal.js
components/ui/filters.js
components/ui/navigation-list.js
constants/documents-database.js
css/components/ui/_navigation-list.scss
hoc/with-intl.js
modules/documents-database.js
modules/index.js
pages/database.js
pages/observations.js
selectors/database/database.js
selectors/database/filters.js

Based on the Observations page.

Producers' documents database

---

components/operators-detail/documentation.js
components/operators-detail/documentation/documents-filter.js
components/operators-detail/observations.js
components/operators-detail/observations/by-category-illegality.js
components/operators-detail/observations/total.js
constants/observations-column-headers.js
css/components/form/checkbox.scss
css/components/ui/_doc-filters.scss
modules/operators-detail.js
pages/observations.js
pages/operators/detail.js
selectors/observations/parsed-table-observations.js
selectors/operators-detail/observations.js
utils/observations.js

Filter by FMU in the operator detail > observations tab.

---

components/ui/card.js

fix card formatting for zero number

---

components/operators-detail/fmus.js
selectors/operators-detail/fmus.js

+ adding `operator_id` for tiles endpoint that will be soon supported.

FMU details: fix bad highlight of totally wrong FMU

---

components/operators-detail/documentation/documents-by-operator.js
selectors/operators-detail/documentation.js

Change documents sort order

---

components/ui/notifications.js
components/ui/static-header.js
components/ui/user-menu-list.js
css/components/page/_static-header.scss
index.js
lang/zu.json
pages/operators/detail.js
pages/operators/edit.js

- ability to manage multiple producers
- show notifications for all holding's producers

Adjust portal for holding accounts

---

components/operators-detail/fmus.js

Show no FMUs message instead of the map if there are no FMUs

---

components/map/legend/component.js
components/map/legend/legend-list/index.js
css/components/map/_legend-list.scss

Load the legend list dynamically as mostly collapsed during initial page loads.

Dynamic legend content loading
